<a href="https://colab.research.google.com/github/VigneshJ19/DL---LAB/blob/main/Assessment%20-%203%20-%20CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning and its Applications - Assessment - 3 - CNN

**NAME :**Vignesh J

**ROLL NO :**20MAI0012

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras import optimizers
from keras import backend as K
import sklearn
from keras.models import load_model
import pandas as pd  
from keras.preprocessing import image
from PIL import Image
import os
import keras
import keras.utils
from keras import utils as np_utils

Using TensorFlow backend.


In [ ]:
import numpy as np
from keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn import metrics
import csv

In [ ]:
img_width, img_height = 150, 150

Dataset link : https://www.kaggle.com/vincee/intel-image-classification-cnn-keras/data?select=seg_train

In [ ]:
train_data_dir = r"C:\Users\VIGNESH J\Downloads\scenery_dataset\seg_train"
test_data_dir = r"C:\Users\VIGNESH J\Downloads\scenery_dataset\seg_train"
nb_train_samples = 14034
nb_test_samples = 3000
epochs = 8
batch_size = 16

if K.image_data_format() == 'channels_first':
    input_shape = (3, img_width, img_height)
else:
    input_shape = (img_width, img_height, 3)

In [ ]:
### Setup the model
model = Sequential()
model.add(Conv2D(32, (3, 3), input_shape=input_shape))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(6))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])
model.summary()


from keras.preprocessing.image import ImageDataGenerator
train_datagen = ImageDataGenerator(
    rescale=1. / 255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True)

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 148, 148, 32)      896       
_________________________________________________________________
activation_1 (Activation)    (None, 148, 148, 32)      0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 74, 74, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 72, 72, 32)        9248      
_________________________________________________________________
activation_2 (Activation)    (None, 72, 72, 32)        0         
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 36, 36, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 34, 34, 64)       

In [ ]:
test_datagen = ImageDataGenerator(rescale=1. / 255)

In [ ]:
### Setup the generators
###fits the model on batches with real-time data augmentation
train_generator = train_datagen.flow_from_directory(
    train_data_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='categorical')

test_generator = test_datagen.flow_from_directory(
    test_data_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='categorical')

Found 14034 images belonging to 6 classes.
Found 14034 images belonging to 6 classes.


In [ ]:
### Build the model
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True


model.fit_generator(
    train_generator,
    steps_per_epoch=nb_train_samples // batch_size,
    epochs=epochs,
    validation_data=test_generator,
    validation_steps=nb_test_samples // batch_size)

Epoch 1/8
877/877 [==============================] - 803s 915ms/step - loss: 1.1464 - accuracy: 0.5598 - val_loss: 1.3165 - val_accuracy: 0.7233
Epoch 2/8
877/877 [==============================] - 343s 391ms/step - loss: 0.8946 - accuracy: 0.6756 - val_loss: 0.8762 - val_accuracy: 0.7236
Epoch 3/8
877/877 [==============================] - 321s 366ms/step - loss: 0.8334 - accuracy: 0.7100 - val_loss: 0.6119 - val_accuracy: 0.7627
Epoch 4/8
877/877 [==============================] - 270s 308ms/step - loss: 0.7927 - accuracy: 0.7258 - val_loss: 0.9296 - val_accuracy: 0.8098
Epoch 5/8
877/877 [==============================] - 246s 280ms/step - loss: 0.7698 - accuracy: 0.7346 - val_loss: 0.2057 - val_accuracy: 0.7831
Epoch 6/8
877/877 [==============================] - 231s 263ms/step - loss: 0.7735 - accuracy: 0.7355 - val_loss: 0.2122 - val_accuracy: 0.8132
Epoch 7/8
877/877 [==============================] - 213s 243ms/step - loss: 0.7770 - accuracy: 0.7440 - val_loss: 0.6712 - val_ac

In [ ]:
### Performance evaluation
score = model.evaluate_generator(test_generator,nb_test_samples/batch_size)
print(" Total: ", len(test_generator.filenames))
print("Loss: ", score[0], "Accuracy: ", score[1])

 Total:  14034
Loss:  0.7028783559799194 Accuracy:  0.8008643388748169


In [ ]:
true_classes = test_generator.classes

In [ ]:
#testing the classifier
y_pred = model.predict(test_generator)
y_pred_labels=np.argmax(y_pred , axis = 1)
print(y_pred_labels)
print("-----------------CONFUSION MATRIX-------------------")

print(confusion_matrix(true_classes,y_pred_labels))  

print("------------------CLASSIFICATION REPORT ------------------")
print(classification_report(true_classes,y_pred_labels))
Y_pred = model.predict_generator(test_generator)



[3 4 1 ... 3 2 2]
-----------------CONFUSION MATRIX-------------------
[[360 379 379 389 302 382]
 [357 343 415 432 296 428]
 [365 370 403 489 307 470]
 [414 373 446 511 320 448]
 [355 352 402 464 274 427]
 [350 416 428 475 300 413]]
------------------CLASSIFICATION REPORT ------------------
              precision    recall  f1-score   support

           0       0.16      0.16      0.16      2191
           1       0.15      0.15      0.15      2271
           2       0.16      0.17      0.17      2404
           3       0.19      0.20      0.19      2512
           4       0.15      0.12      0.13      2274
           5       0.16      0.17      0.17      2382

    accuracy                           0.16     14034
   macro avg       0.16      0.16      0.16     14034
weighted avg       0.16      0.16      0.16     14034



In [ ]:
# Predicting the classes
test_image = image.load_img(r'C:\Users\VIGNESH J\Downloads\scenery_dataset\seg_pred\101.jpg', target_size = (150, 150))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = model.predict(test_image)
print(result)

[[0. 0. 1. 0. 0. 0.]]
